### ISSUE TITLE
USER STORY: provide anonymous feedback

### ISSUE THREAD

**Issue by ClDaly2904** [ClDaly2904/my-first-agile-project#3]
## User Story:
As a **user** I can **choose to hide my identity in a poll** so that **I can give anonymous feedback**

## Acceptance Criteria:
* The option should be provided as a checkbox
* The checkbox should be "checked" by default
* The option should appear next to the submit button
* After submitting, the default submission confirmation should be adjusted to include username

## Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to include the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
