### ISSUE TITLE
USER STORY: publish a poll

### ISSUE THREAD

**Issue by ClDaly2904** [ClDaly2904/my-first-agile-project#4]
## User Story:
As an **administrator** I can **pick the expiry date when publishing a poll** so that **the poll is automatically hidden**

## Acceptance Criteria:
* The poll should disappear at 11:59PM on the target date
* The real estate of the "Poll" should be reserved on the home page, a message saying "Stay tuned, a new poll is coming soon" should appear if no other poll is active
* The administrator expiry date should be at least three days after the current date

## Tasks
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to check that the expiry date is at least after three days
- [ ] Create a job to check for expired polls everyday at 11:59PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
